### ISSUE TITLE
yoo is this a gaming related protocol? 

### ISSUE THREAD

**Issue by viprocket1** [raindrops-protocol/raindrops#1]

**Comment by staccDOTsol** [comment]
Should join office hours :) 

J talks about it briefly

Recording https://solanalabs.zoom.us/rec/share/ku7nPg3T-vSjQCZ4lBkLtIQk3KEqmeztIfBVNc6ccAuuFrStCMniU4qzGbiZNPmf.vI__GVq-EvlcbmG3 Passcode: y3$FJR0E

**Comment by bhgames** [comment]
yes

**Comment by long-banana** [comment]
https://long-banana.gitbook.io/raindrops/ . Check out the gitbook
